export const genreOptions = [
    { id: 1, value: 'fiction', label: 'Fiction' },
    { id: 2, value: 'flashFiction', label: 'Flash Fiction' },
    { id: 3, value: 'fiction', label: 'Fiction (Micro)' },
    { id: 4, value: 'nonfiction', label: 'Nonfiction' },
    { id: 5, value: 'flashCNF', label: 'Flash Nonfiction' },
    { id: 6, value: 'poetry', label: 'Poetry' },
    { id: 20, value: 'prosePoetry', label: 'Prose Poetry' },
    { id: 7, value: 'hybrid', label: 'Hybrid' },
    { id: 8, value: 'review', label: 'Review' },
    { id: 9, value: 'interview', label: 'Interview' },
    { id: 10, value: 'translations', label: 'Translation' },
    { id: 11, value: 'art', label: 'Art' },
    { id: 12, value: 'photography', label: 'Photography' },
    { id: 13, value: 'humor', label: 'Humor' },
    { id: 14, value: 'play', label: 'Play' },
    { id: 15, value: 'comics', label: 'Comics' },
    { id: 16, value: 'audio', label: 'Audio' },
    { id: 17, value: 'video', label: 'Video' },
    { id: 18, value: 'game', label: 'Game' },
    { id: 19, value: 'anything', label: 'Wtf is genre, send anything' },
  ];